before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: us8UfDOMvnfNqRoTvKKb07DCoySwMTJ0Co1Jt1v3kTRwPrxe/4ko7iubLlqbFw2PWfs86neMwngEo13DVmvnNU5z5YQEj6DJR806hUWpVZUl1b3ZOjTGceiorI9NNy0GapcFnGDKDVTiWzESQVk5KlyRLqFgiHD9fR0o1PEJcRSAg+YreM7rM3beFLtZNUTBQ4eCFtOUnis/voHwJOvbZjVoCGIeZIn+d30SybF94OcX9Mw3FwQZaRJozhGzsWJ31REuXLB2RuEtJQWQGshj6f/x1ocUjuX9FpnBVdeXQcuaOqpVuhs931il4Q9+O+NG5F9iSE3PVX34nCJAtQhdKGowb7Q0I5fBLkEuOGw6qW5WiVcY+SNpzb5kFUc5GyLIixn4Xy238mLPdstxbg+gTxSWW1B3/4VvbEnuz8mK5RbG33uf4QS4rC9qUmfEnhf6BkqxJejkiuQwmV/oI8MZ7H+04vAnQvauXmi49lqRxD78JM9okbsIPULQ+LML9E5hWDm4rf/zyE6K9lN4cdPQojR4nvTEUMVVeKjEXkGa0RmG8IPt+frpKXcaj+/fgIl/DCxuyTdN2GE6++F3783aUz+Aa9hxcVbdEFQOT/4K7mhMwI3p6seidEt1W650NKf+C2lNil05K8POqJvDWGdYYqMj4n6CIGVgR7fLX3wgvdg= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
